# Generated by Django 4.1.5 on 2023-01-12 22:05

import core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(max_length=100, validators=[core.validators.Validators.alphabet_validator]),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(max_length=100, validators=[core.validators.Validators.alphabet_validator]),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, validators=[core.validators.Validators.phone_number_validator]),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.ForeignKey(default='2', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.role'),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(max_length=100, validators=[core.validators.Validators.alphabet_validator]),
        ),
    ]
